Adds two methods to get the contents of the MultiUrlPicker's links.
EndzoneSoftware/Umbraco.Extensions pull request #15
Opened 2017-08-31 11:45 UTC by filipesousa20

Add a couple of utility methods. Avoids having to check the links for null. Still will need to check the result for null.

2017-09-06 14:54 UTC, ondrejpialek commented on Endzone.Umbraco.Extensions/PublishedContentExtensions/MultiUrlPicker.cs
> +            return linksContent.Any() ? linksContent.First() : default(IPublishedContent);
This can just say `linksContent.FirstOrDefault()`

2017-09-06 14:54 UTC, ondrejpialek commented on Endzone.Umbraco.Extensions/PublishedContentExtensions/MultiUrlPicker.cs
> +                    linksContent.Add(umbracoHelper.TypedContent(link.Id));
Is this potentially unsafe when the link is external? I think an additional check needs to be added to the if statement above.

2017-09-06 20:10 UTC, filipesousa20 commented
@ondrejpialek your suggestions make sense so I added them in. Please review.

2017-09-06 20:56 UTC, ondrejpialek requested changes

2017-09-06 20:56 UTC, ondrejpialek commented on Endzone.Umbraco.Extensions/PublishedContentExtensions/MultiUrlPicker.cs
> +        /// Gets the links as a collection of IPublishedContent. Check for null.
Sorry this slipped my attention earlier: The comment says "Check for null" but it's safe here - you always return a list.

2017-09-07 16:01 UTC, filipesousa20 commented
@ondrejpialek that is true. Just removed it.

2017-09-07 16:17 UTC, ondrejpialek approved these changes

2017-09-07 16:17 UTC, merged